export type Grade = 4 | 6;
export type DifficultyLevel = "easy" | "medium" | "hard";

export type Question = {
  id: string;
  itemId: string;
  batteryId: string;
  grade: Grade;
  domain: string;
  subskill: string;
  difficultyLevel: DifficultyLevel;
  prompt: string;
  options: string[];
  correctIndex: number;
  rationale: string;
};

function q(item: Question): Question {
  return item;
}

export const QUESTION_SETS: Record<Grade, Question[]> = {
  4: [
    q({ id: "g4-i1", itemId: "I4-PD-01", batteryId: "intelligence_4", grade: 4, domain: "intelligence_4", subskill: "pattern detection", difficultyLevel: "easy", prompt: "Продолжи: ○, □, ○, □, ...", options: ["○", "△", "☆", "⬟"], correctIndex: 0, rationale: "Базовое чередование ABAB." }),
    q({ id: "g4-i2", itemId: "I4-PD-02", batteryId: "intelligence_4", grade: 4, domain: "intelligence_4", subskill: "pattern detection", difficultyLevel: "easy", prompt: "Какое число дальше: 4, 7, 10, ...", options: ["11", "12", "13", "14"], correctIndex: 2, rationale: "Шаг +3." }),
    q({ id: "g4-i3", itemId: "I4-TR-01", batteryId: "intelligence_4", grade: 4, domain: "intelligence_4", subskill: "transformation", difficultyLevel: "medium", prompt: "Стрелка смотрела вверх. После поворота на 90° по часовой — куда смотрит?", options: ["влево", "вправо", "вниз", "вверх"], correctIndex: 1, rationale: "Мысленный поворот." }),
    q({ id: "g4-i4", itemId: "I4-TR-02", batteryId: "intelligence_4", grade: 4, domain: "intelligence_4", subskill: "transformation", difficultyLevel: "medium", prompt: "Квадрат повернули на 180°. Что верно?", options: ["станет треугольником", "останется тем же", "исчезнет", "станет зеркальным"], correctIndex: 1, rationale: "Инвариант фигуры при 180°." }),
    q({ id: "g4-i5", itemId: "I4-AB-01", batteryId: "intelligence_4", grade: 4, domain: "intelligence_4", subskill: "abstraction", difficultyLevel: "medium", prompt: "Найди лишнее: 2, 4, 6, 9", options: ["2", "4", "6", "9"], correctIndex: 3, rationale: "Три чётных, одно нечётное." }),
    q({ id: "g4-i6", itemId: "I4-MR-01", batteryId: "intelligence_4", grade: 4, domain: "intelligence_4", subskill: "missing-part reasoning", difficultyLevel: "medium", prompt: "В ряду A, B, C, _, E пропущена буква:", options: ["D", "F", "G", "B"], correctIndex: 0, rationale: "Пропуск в линейном порядке." }),
    q({ id: "g4-i7", itemId: "I4-PD-03", batteryId: "intelligence_4", grade: 4, domain: "intelligence_4", subskill: "pattern detection", difficultyLevel: "easy", prompt: "Продолжи: ▲ ▼ ▲ ▼ ...", options: ["▲", "▼", "■", "○"], correctIndex: 0, rationale: "Чередование из двух элементов." }),
    q({ id: "g4-i8", itemId: "I4-TR-03", batteryId: "intelligence_4", grade: 4, domain: "intelligence_4", subskill: "transformation", difficultyLevel: "hard", prompt: "Стрелка делает три поворота по 90° по часовой. Если сначала была вверх, где будет?", options: ["вверх", "вправо", "вниз", "влево"], correctIndex: 3, rationale: "Составное преобразование 270°." }),
    q({ id: "g4-i9", itemId: "I4-AB-02", batteryId: "intelligence_4", grade: 4, domain: "intelligence_4", subskill: "abstraction", difficultyLevel: "medium", prompt: "Что общего у квадрата и прямоугольника?", options: ["только 3 угла", "4 стороны", "все стороны разные", "нет углов"], correctIndex: 1, rationale: "Выделение общего признака." }),
    q({ id: "g4-i10", itemId: "I4-MR-02", batteryId: "intelligence_4", grade: 4, domain: "intelligence_4", subskill: "missing-part reasoning", difficultyLevel: "medium", prompt: "2, 4, _, 8. Какое число пропущено?", options: ["5", "6", "7", "9"], correctIndex: 1, rationale: "Ряд чётных." }),
    q({ id: "g4-i11", itemId: "I4-PD-04", batteryId: "intelligence_4", grade: 4, domain: "intelligence_4", subskill: "pattern detection", difficultyLevel: "hard", prompt: "Ряд: 1, 3, 6, 10, ... Какое число дальше?", options: ["12", "14", "15", "16"], correctIndex: 2, rationale: "Нарастающие прибавления +2,+3,+4." }),
    q({ id: "g4-i12", itemId: "I4-MR-03", batteryId: "intelligence_4", grade: 4, domain: "intelligence_4", subskill: "missing-part reasoning", difficultyLevel: "easy", prompt: "Круг, треугольник, квадрат, круг, треугольник, ...", options: ["квадрат", "круг", "ромб", "звезда"], correctIndex: 0, rationale: "Цикл из трёх фигур." }),
    q({ id: "g4-i13", itemId: "I4-AB-03", batteryId: "intelligence_4", grade: 4, domain: "intelligence_4", subskill: "abstraction", difficultyLevel: "hard", prompt: "Выбери правило, которое подходит к ряду 5, 10, 20, 40", options: ["каждый раз +5", "каждый раз ×2", "каждый раз +10", "чередуются +5 и ×2"], correctIndex: 1, rationale: "Выделение операции как абстрактного правила." }),
    q({ id: "g4-i14", itemId: "I4-TR-04", batteryId: "intelligence_4", grade: 4, domain: "intelligence_4", subskill: "transformation", difficultyLevel: "medium", prompt: "Букву П отразили в зеркале по вертикали. Какой вариант верный?", options: ["та же П", "перевёрнутая П", "зеркальная П", "Т"], correctIndex: 0, rationale: "Симметричная фигура остаётся той же." }),
    q({ id: "g4-i15", itemId: "I4-MR-04", batteryId: "intelligence_4", grade: 4, domain: "intelligence_4", subskill: "missing-part reasoning", difficultyLevel: "hard", prompt: "В таблице по строкам добавляют +2: 3,5,7 / 4,6,8 / 6,8, _. Что в пустой клетке?", options: ["9", "10", "11", "12"], correctIndex: 1, rationale: "Комбинация табличного и линейного правила." }),

    q({ id: "g4-l1", itemId: "L4-CL-01", batteryId: "logic_4", grade: 4, domain: "logic_4", subskill: "classification", difficultyLevel: "easy", prompt: "Что лишнее: яблоко, груша, слива, стол?", options: ["яблоко", "груша", "слива", "стол"], correctIndex: 3, rationale: "Классификация по категории." }),
    q({ id: "g4-l2", itemId: "L4-OR-01", batteryId: "logic_4", grade: 4, domain: "logic_4", subskill: "ordering", difficultyLevel: "easy", prompt: "Понедельник, вторник, среда, ...", options: ["четверг", "пятница", "суббота", "воскресенье"], correctIndex: 0, rationale: "Порядок дней недели." }),
    q({ id: "g4-l3", itemId: "L4-RC-01", batteryId: "logic_4", grade: 4, domain: "logic_4", subskill: "relation consistency", difficultyLevel: "medium", prompt: "Котёнок — кошка, щенок — ...", options: ["собака", "лиса", "коза", "волк"], correctIndex: 0, rationale: "Пара «детёныш—взрослое животное»." }),
    q({ id: "g4-l4", itemId: "L4-INF-01", batteryId: "logic_4", grade: 4, domain: "logic_4", subskill: "simple/advanced inference", difficultyLevel: "medium", prompt: "Все карандаши пишут. Этот предмет — карандаш. Что верно?", options: ["он пишет", "он не пишет", "он игрушка", "ничего нельзя сказать"], correctIndex: 0, rationale: "Простой силлогизм." }),
    q({ id: "g4-l5", itemId: "L4-OR-02", batteryId: "logic_4", grade: 4, domain: "logic_4", subskill: "ordering", difficultyLevel: "medium", prompt: "Если А выше Б, а Б выше В, кто самый высокий?", options: ["А", "Б", "В", "нельзя узнать"], correctIndex: 0, rationale: "Транзитивное упорядочивание." }),
    q({ id: "g4-l6", itemId: "L4-RC-02", batteryId: "logic_4", grade: 4, domain: "logic_4", subskill: "relation consistency", difficultyLevel: "easy", prompt: "Книга : читать = мяч : ...", options: ["играть", "рисовать", "прыгать", "писать"], correctIndex: 0, rationale: "Функциональная аналогия." }),
    q({ id: "g4-l7", itemId: "L4-INF-02", batteryId: "logic_4", grade: 4, domain: "logic_4", subskill: "simple/advanced inference", difficultyLevel: "hard", prompt: "Если идёт дождь, то улица мокрая. Улица мокрая. Какой вывод самый точный?", options: ["точно был дождь", "могла быть другая причина", "дождя точно не было", "улица сухая"], correctIndex: 1, rationale: "Не утверждать обратное без основания." }),
    q({ id: "g4-l8", itemId: "L4-CL-02", batteryId: "logic_4", grade: 4, domain: "logic_4", subskill: "classification", difficultyLevel: "easy", prompt: "Что общего у слов «стол», «стул», «шкаф»?", options: ["животные", "мебель", "транспорт", "посуда"], correctIndex: 1, rationale: "Категориальная группировка." }),
    q({ id: "g4-l9", itemId: "L4-OR-03", batteryId: "logic_4", grade: 4, domain: "logic_4", subskill: "ordering", difficultyLevel: "medium", prompt: "Если сегодня вторник, какой день будет через 3 дня?", options: ["четверг", "пятница", "суббота", "воскресенье"], correctIndex: 1, rationale: "Пошаговый счёт по календарю." }),
    q({ id: "g4-l10", itemId: "L4-INF-03", batteryId: "logic_4", grade: 4, domain: "logic_4", subskill: "simple/advanced inference", difficultyLevel: "medium", prompt: "Все розы — цветы. Этот предмет — роза. Значит...", options: ["это дерево", "это цветок", "это фрукт", "вывода нет"], correctIndex: 1, rationale: "Дедуктивный вывод." }),
    q({ id: "g4-l11", itemId: "L4-RC-03", batteryId: "logic_4", grade: 4, domain: "logic_4", subskill: "relation consistency", difficultyLevel: "hard", prompt: "А больше Б, Б больше В, В больше Г. Кто самый маленький?", options: ["А", "Б", "В", "Г"], correctIndex: 3, rationale: "Цепочка отношений >." }),
    q({ id: "g4-l12", itemId: "L4-CL-03", batteryId: "logic_4", grade: 4, domain: "logic_4", subskill: "classification", difficultyLevel: "medium", prompt: "Найди лишнее: квадрат, прямоугольник, круг, треугольник", options: ["квадрат", "прямоугольник", "круг", "треугольник"], correctIndex: 2, rationale: "Один без углов." }),
    q({ id: "g4-l13", itemId: "L4-OR-04", batteryId: "logic_4", grade: 4, domain: "logic_4", subskill: "ordering", difficultyLevel: "hard", prompt: "В очереди Миша стоит раньше Оли, но позже Вани. Кто из них первый?", options: ["Миша", "Оля", "Ваня", "определить нельзя"], correctIndex: 2, rationale: "Двойное ограничение порядка." }),
    q({ id: "g4-l14", itemId: "L4-RC-04", batteryId: "logic_4", grade: 4, domain: "logic_4", subskill: "relation consistency", difficultyLevel: "medium", prompt: "Ложка : суп = кисть : ...", options: ["краска", "бумага", "рисунок", "книга"], correctIndex: 2, rationale: "Инструмент — результат действия." }),
    q({ id: "g4-l15", itemId: "L4-INF-04", batteryId: "logic_4", grade: 4, domain: "logic_4", subskill: "simple/advanced inference", difficultyLevel: "hard", prompt: "Если на улице снег, то холодно. Сейчас не холодно. Что наиболее логично?", options: ["снег идёт", "снег не идёт", "может быть снег и жара", "вывода нет"], correctIndex: 1, rationale: "Отрицание следствия даёт отрицание основания." }),

    q({ id: "g4-m1", itemId: "M4-NP-01", batteryId: "math_aptitude_4", grade: 4, domain: "math_aptitude_4", subskill: "number pattern", difficultyLevel: "easy", prompt: "Продолжи ряд: 3, 6, 9, ...", options: ["10", "11", "12", "13"], correctIndex: 2, rationale: "Шаг +3." }),
    q({ id: "g4-m2", itemId: "M4-QC-01", batteryId: "math_aptitude_4", grade: 4, domain: "math_aptitude_4", subskill: "quantity comparison", difficultyLevel: "easy", prompt: "Какое число больше: 56 или 65?", options: ["56", "65", "равны", "нельзя сравнить"], correctIndex: 1, rationale: "Сравнение двузначных чисел." }),
    q({ id: "g4-m3", itemId: "M4-PR-01", batteryId: "math_aptitude_4", grade: 4, domain: "math_aptitude_4", subskill: "proportional reasoning", difficultyLevel: "medium", prompt: "2 тетради стоят 20 рублей. Сколько стоят 5 таких тетрадей?", options: ["40", "45", "50", "60"], correctIndex: 2, rationale: "Прямая пропорция." }),
    q({ id: "g4-m4", itemId: "M4-SQM-01", batteryId: "math_aptitude_4", grade: 4, domain: "math_aptitude_4", subskill: "structural quantitative modeling", difficultyLevel: "medium", prompt: "У Оли 14 наклеек, у Пети на 5 меньше. Сколько у Пети?", options: ["7", "8", "9", "10"], correctIndex: 2, rationale: "Модель «на ... меньше»." }),
    q({ id: "g4-m5", itemId: "M4-SQR-01", batteryId: "math_aptitude_4", grade: 4, domain: "math_aptitude_4", subskill: "spatial-quantitative reasoning", difficultyLevel: "medium", prompt: "У прямоугольника 4 стороны. Сколько углов у двух таких прямоугольников вместе?", options: ["4", "6", "8", "10"], correctIndex: 2, rationale: "Пространственный счёт объектов." }),
    q({ id: "g4-m6", itemId: "M4-NP-02", batteryId: "math_aptitude_4", grade: 4, domain: "math_aptitude_4", subskill: "number pattern", difficultyLevel: "medium", prompt: "2, 5, 9, 14, ... Какое число дальше?", options: ["18", "19", "20", "21"], correctIndex: 2, rationale: "Прибавления +3,+4,+5." }),
    q({ id: "g4-m7", itemId: "M4-QC-02", batteryId: "math_aptitude_4", grade: 4, domain: "math_aptitude_4", subskill: "quantity comparison", difficultyLevel: "easy", prompt: "Что ближе к 100?", options: ["91", "96", "89", "84"], correctIndex: 1, rationale: "Сравнение расстояний до 100." }),
    q({ id: "g4-m8", itemId: "M4-PR-02", batteryId: "math_aptitude_4", grade: 4, domain: "math_aptitude_4", subskill: "proportional reasoning", difficultyLevel: "hard", prompt: "Если 3 одинаковых набора содержат 18 карандашей, сколько карандашей в 5 наборах?", options: ["24", "28", "30", "32"], correctIndex: 2, rationale: "Переход через единичный набор." }),
    q({ id: "g4-m9", itemId: "M4-SQM-02", batteryId: "math_aptitude_4", grade: 4, domain: "math_aptitude_4", subskill: "structural quantitative modeling", difficultyLevel: "medium", prompt: "В коробке было 20 фломастеров. 7 взяли и 3 добавили. Сколько стало?", options: ["14", "15", "16", "17"], correctIndex: 2, rationale: "Двухшаговая количественная модель." }),
    q({ id: "g4-m10", itemId: "M4-SQR-02", batteryId: "math_aptitude_4", grade: 4, domain: "math_aptitude_4", subskill: "spatial-quantitative reasoning", difficultyLevel: "hard", prompt: "Квадрат разделили на 4 равные части. Закрасили 3 части. Какая доля закрашена?", options: ["1/2", "3/4", "2/3", "4/3"], correctIndex: 1, rationale: "Связь площади и дроби." }),
    q({ id: "g4-m11", itemId: "M4-NP-03", batteryId: "math_aptitude_4", grade: 4, domain: "math_aptitude_4", subskill: "number pattern", difficultyLevel: "easy", prompt: "Продолжи: 10, 20, 30, ...", options: ["35", "40", "45", "50"], correctIndex: 1, rationale: "Шаг +10." }),
    q({ id: "g4-m12", itemId: "M4-QC-03", batteryId: "math_aptitude_4", grade: 4, domain: "math_aptitude_4", subskill: "quantity comparison", difficultyLevel: "medium", prompt: "Что больше: 3/4 или 2/3?", options: ["3/4", "2/3", "равны", "нельзя сравнить"], correctIndex: 0, rationale: "Сравнение простых дробей." }),
    q({ id: "g4-m13", itemId: "M4-PR-03", batteryId: "math_aptitude_4", grade: 4, domain: "math_aptitude_4", subskill: "proportional reasoning", difficultyLevel: "medium", prompt: "1 кг яблок стоит 80 рублей. Сколько стоят 3 кг?", options: ["160", "220", "240", "260"], correctIndex: 2, rationale: "Пропорция «цена за единицу»." }),
    q({ id: "g4-m14", itemId: "M4-SQM-03", batteryId: "math_aptitude_4", grade: 4, domain: "math_aptitude_4", subskill: "structural quantitative modeling", difficultyLevel: "hard", prompt: "В классе 24 ученика. 1/3 участвует в кружке. Сколько это учеников?", options: ["6", "8", "10", "12"], correctIndex: 1, rationale: "Модель «доля от целого»." }),
    q({ id: "g4-m15", itemId: "M4-SQR-03", batteryId: "math_aptitude_4", grade: 4, domain: "math_aptitude_4", subskill: "spatial-quantitative reasoning", difficultyLevel: "medium", prompt: "У куба 6 граней. Сколько граней у двух кубов?", options: ["10", "12", "14", "16"], correctIndex: 1, rationale: "Пространственно-количественный подсчёт." }),
  ],
  6: [
    q({ id: "g6-i1", itemId: "I6-PD-01", batteryId: "intelligence_6", grade: 6, domain: "intelligence_6", subskill: "pattern detection", difficultyLevel: "medium", prompt: "Ряд: 2, 6, 12, 20, ... Выбери следующее число.", options: ["28", "30", "32", "34"], correctIndex: 1, rationale: "n(n+1): 1*2,2*3,3*4..." }),
    q({ id: "g6-i2", itemId: "I6-TR-01", batteryId: "intelligence_6", grade: 6, domain: "intelligence_6", subskill: "transformation", difficultyLevel: "medium", prompt: "Фигуру повернули на 90° и затем отразили по вертикали. Какое преобразование эквивалентно?", options: ["поворот на 180°", "отражение по диагонали", "сдвиг", "масштабирование"], correctIndex: 1, rationale: "Композиция преобразований." }),
    q({ id: "g6-i3", itemId: "I6-AB-01", batteryId: "intelligence_6", grade: 6, domain: "intelligence_6", subskill: "abstraction", difficultyLevel: "hard", prompt: "Выбери правило ряда: 3, 8, 15, 24, ...", options: ["+5, +7, +9 ...", "×2 -1", "+4 всегда", "чередуется +5 и +6"], correctIndex: 0, rationale: "Абстракция по растущему шагу." }),
    q({ id: "g6-i4", itemId: "I6-MR-01", batteryId: "intelligence_6", grade: 6, domain: "intelligence_6", subskill: "missing-part reasoning", difficultyLevel: "medium", prompt: "A1, C2, E3, _, I5. Что пропущено?", options: ["F4", "G4", "H4", "G5"], correctIndex: 1, rationale: "Одновременный шаг по буквам и числам." }),
    q({ id: "g6-i5", itemId: "I6-PD-02", batteryId: "intelligence_6", grade: 6, domain: "intelligence_6", subskill: "pattern detection", difficultyLevel: "hard", prompt: "1, 2, 4, 7, 11, ...", options: ["14", "15", "16", "17"], correctIndex: 2, rationale: "Прибавления +1,+2,+3,+4,+5." }),
    q({ id: "g6-i6", itemId: "I6-TR-02", batteryId: "intelligence_6", grade: 6, domain: "intelligence_6", subskill: "transformation", difficultyLevel: "hard", prompt: "Точка (2;3) смещается каждый шаг на (+2;−1). Где она будет через 3 шага?", options: ["(6;1)", "(8;0)", "(7;1)", "(8;1)"], correctIndex: 1, rationale: "Координатное преобразование." }),
    q({ id: "g6-i7", itemId: "I6-AB-02", batteryId: "intelligence_6", grade: 6, domain: "intelligence_6", subskill: "abstraction", difficultyLevel: "medium", prompt: "Оператор ◇ означает «умножить на 2 и прибавить 3». Чему равно 7◇?", options: ["14", "16", "17", "19"], correctIndex: 2, rationale: "Понимание символического оператора." }),
    q({ id: "g6-i8", itemId: "I6-MR-02", batteryId: "intelligence_6", grade: 6, domain: "intelligence_6", subskill: "missing-part reasoning", difficultyLevel: "hard", prompt: "В матрице по строкам число сторон +1, а цвет чередуется. В пустой клетке нужен:", options: ["светлый пятиугольник", "тёмный пятиугольник", "светлый шестиугольник", "тёмный шестиугольник"], correctIndex: 3, rationale: "Интеграция двух признаков." }),
    q({ id: "g6-i9", itemId: "I6-PD-03", batteryId: "intelligence_6", grade: 6, domain: "intelligence_6", subskill: "pattern detection", difficultyLevel: "medium", prompt: "B2, D4, F6, ...", options: ["G7", "H8", "I8", "I9"], correctIndex: 1, rationale: "Буквы через одну, числа +2." }),
    q({ id: "g6-i10", itemId: "I6-TR-03", batteryId: "intelligence_6", grade: 6, domain: "intelligence_6", subskill: "transformation", difficultyLevel: "medium", prompt: "Что эквивалентно двум последовательным поворотам на 90° по часовой?", options: ["поворот на 90°", "поворот на 180°", "поворот на 270°", "отражение"], correctIndex: 1, rationale: "Композиция поворотов." }),
    q({ id: "g6-i11", itemId: "I6-AB-03", batteryId: "intelligence_6", grade: 6, domain: "intelligence_6", subskill: "abstraction", difficultyLevel: "hard", prompt: "f(n+1)=2f(n)-1, f(1)=4. Найди f(4).", options: ["21", "23", "25", "27"], correctIndex: 2, rationale: "f(2)=7, f(3)=13, f(4)=25; верный вариант — 25." }),
    q({ id: "g6-i12", itemId: "I6-MR-03", batteryId: "intelligence_6", grade: 6, domain: "intelligence_6", subskill: "missing-part reasoning", difficultyLevel: "medium", prompt: "7, 14, 28, _, 112", options: ["42", "54", "56", "64"], correctIndex: 2, rationale: "Удвоение, пропуск в ряду." }),
    q({ id: "g6-i13", itemId: "I6-PD-04", batteryId: "intelligence_6", grade: 6, domain: "intelligence_6", subskill: "pattern detection", difficultyLevel: "hard", prompt: "Последовательность: 1, 4, 10, 22, ...", options: ["34", "40", "46", "48"], correctIndex: 2, rationale: "×2+2, ×2+2, ..." }),
    q({ id: "g6-i14", itemId: "I6-TR-04", batteryId: "intelligence_6", grade: 6, domain: "intelligence_6", subskill: "transformation", difficultyLevel: "hard", prompt: "Сначала отражение по горизонтали, затем поворот на 180°. Это эквивалентно:", options: ["отражению по вертикали", "повороту на 90°", "масштабированию", "сдвигу"], correctIndex: 0, rationale: "Композиции симметрий." }),
    q({ id: "g6-i15", itemId: "I6-MR-04", batteryId: "intelligence_6", grade: 6, domain: "intelligence_6", subskill: "missing-part reasoning", difficultyLevel: "hard", prompt: "Если чётные фигуры светлые, нечётные тёмные, и число сторон растёт на 1: 3(тёмн),4(светл),5(тёмн),_.", options: ["6 тёмн", "6 светл", "7 светл", "7 тёмн"], correctIndex: 1, rationale: "Пропуск при двойном правиле." }),
    q({ id: "g6-i16", itemId: "I6-AB-04", batteryId: "intelligence_6", grade: 6, domain: "intelligence_6", subskill: "abstraction", difficultyLevel: "medium", prompt: "Какое выражение задаёт ряд 5, 11, 17, 23 ...", options: ["6n", "6n-1", "5n+1", "n²+4"], correctIndex: 1, rationale: "Линейная формула члена." }),
    q({ id: "g6-i17", itemId: "I6-PD-05", batteryId: "intelligence_6", grade: 6, domain: "intelligence_6", subskill: "pattern detection", difficultyLevel: "medium", prompt: "AB, BCA, CABC, ... Что дальше?", options: ["ABCAB", "DABCD", "ABCABC", "DCBA"], correctIndex: 0, rationale: "Наращивание шаблона." }),
    q({ id: "g6-i18", itemId: "I6-TR-05", batteryId: "intelligence_6", grade: 6, domain: "intelligence_6", subskill: "transformation", difficultyLevel: "hard", prompt: "Квадрат повернули на 90°, потом ещё на 270°. Что верно?", options: ["положение не изменилось", "эквивалентно отражению", "эквивалентно повороту на 180°", "определить нельзя"], correctIndex: 0, rationale: "Суммарно 360°." }),
    q({ id: "g6-i19", itemId: "I6-MR-05", batteryId: "intelligence_6", grade: 6, domain: "intelligence_6", subskill: "missing-part reasoning", difficultyLevel: "medium", prompt: "2, 3, 5, 9, 17, ...", options: ["25", "31", "33", "35"], correctIndex: 2, rationale: "×2−1 повторяется." }),
    q({ id: "g6-i20", itemId: "I6-AB-05", batteryId: "intelligence_6", grade: 6, domain: "intelligence_6", subskill: "abstraction", difficultyLevel: "hard", prompt: "Если a→b означает a+b+ab, чему равно 2→3?", options: ["9", "10", "11", "12"], correctIndex: 2, rationale: "Абстрактная бинарная операция." }),

    q({ id: "g6-l1", itemId: "L6-CL-01", batteryId: "logic_6", grade: 6, domain: "logic_6", subskill: "classification", difficultyLevel: "medium", prompt: "Выбери набор, где все элементы одного логического класса:", options: ["квадрат, треугольник, число", "дробь, процент, десятичная дробь", "книга, чтение, библиотека", "зима, январь, холодно"], correctIndex: 1, rationale: "Строгая классификация математических форм записи." }),
    q({ id: "g6-l2", itemId: "L6-OR-01", batteryId: "logic_6", grade: 6, domain: "logic_6", subskill: "ordering", difficultyLevel: "medium", prompt: "Если K раньше L, L раньше M, а M раньше N, кто идёт вторым?", options: ["K", "L", "M", "N"], correctIndex: 1, rationale: "Линейный порядок из цепочки." }),
    q({ id: "g6-l3", itemId: "L6-RC-01", batteryId: "logic_6", grade: 6, domain: "logic_6", subskill: "relation consistency", difficultyLevel: "hard", prompt: "Все A — B. Ни один B не является C. Что обязательно верно?", options: ["Некоторые A — C", "Ни один A не является C", "Все C — A", "Вывода нет"], correctIndex: 1, rationale: "Связность отношений множеств." }),
    q({ id: "g6-l4", itemId: "L6-INF-01", batteryId: "logic_6", grade: 6, domain: "logic_6", subskill: "simple/advanced inference", difficultyLevel: "hard", prompt: "Если P→Q. Не Q. Что следует?", options: ["P", "Не P", "Q", "Вывод невозможен"], correctIndex: 1, rationale: "Modus tollens." }),
    q({ id: "g6-l5", itemId: "L6-INF-02", batteryId: "logic_6", grade: 6, domain: "logic_6", subskill: "simple/advanced inference", difficultyLevel: "hard", prompt: "Если P→Q и Q→R, при истинном P получаем:", options: ["не R", "R", "не Q", "Q и не R"], correctIndex: 1, rationale: "Цепочка импликаций." }),
    q({ id: "g6-l6", itemId: "L6-RC-02", batteryId: "logic_6", grade: 6, domain: "logic_6", subskill: "relation consistency", difficultyLevel: "medium", prompt: "Некоторые M — N. Что обязательно верно?", options: ["Все M — N", "Некоторые N — M", "Ни один N — M", "Все N — M"], correctIndex: 1, rationale: "Симметрия существования." }),
    q({ id: "g6-l7", itemId: "L6-CL-02", batteryId: "logic_6", grade: 6, domain: "logic_6", subskill: "classification", difficultyLevel: "medium", prompt: "Что лишнее: аксиома, теорема, доказательство, яблоко?", options: ["аксиома", "теорема", "доказательство", "яблоко"], correctIndex: 3, rationale: "Один элемент вне научно-логического класса." }),
    q({ id: "g6-l8", itemId: "L6-OR-02", batteryId: "logic_6", grade: 6, domain: "logic_6", subskill: "ordering", difficultyLevel: "hard", prompt: "A старше B, B старше C, D старше A. Кто самый младший?", options: ["A", "B", "C", "D"], correctIndex: 2, rationale: "Порядок по отношению «старше»." }),
    q({ id: "g6-l9", itemId: "L6-INF-03", batteryId: "logic_6", grade: 6, domain: "logic_6", subskill: "simple/advanced inference", difficultyLevel: "medium", prompt: "Либо X, либо Y. Не X. Следовательно:", options: ["не Y", "Y", "X", "ни X, ни Y"], correctIndex: 1, rationale: "Дизъюнктивный силлогизм." }),
    q({ id: "g6-l10", itemId: "L6-RC-03", batteryId: "logic_6", grade: 6, domain: "logic_6", subskill: "relation consistency", difficultyLevel: "hard", prompt: "Все R — S. Некоторые S — T. Какой вывод корректен?", options: ["Все R — T", "Некоторые T — R", "R и T могут не пересекаться", "Ни один R — S"], correctIndex: 2, rationale: "Проверка недоопределённости связи." }),
    q({ id: "g6-l11", itemId: "L6-CL-03", batteryId: "logic_6", grade: 6, domain: "logic_6", subskill: "classification", difficultyLevel: "easy", prompt: "Что относится к аргументам, а не к выводу?", options: ["посылки", "следствие", "результат", "заключение"], correctIndex: 0, rationale: "Базовая терминология рассуждений." }),
    q({ id: "g6-l12", itemId: "L6-INF-04", batteryId: "logic_6", grade: 6, domain: "logic_6", subskill: "simple/advanced inference", difficultyLevel: "hard", prompt: "Если верно «Не (A и B)», что эквивалентно?", options: ["не A и не B", "не A или не B", "A или B", "A и не B"], correctIndex: 1, rationale: "Закон де Моргана." }),
    q({ id: "g6-l13", itemId: "L6-OR-03", batteryId: "logic_6", grade: 6, domain: "logic_6", subskill: "ordering", difficultyLevel: "medium", prompt: "В расписании математика раньше физики, а физика раньше химии. Что верно?", options: ["химия раньше математики", "математика раньше химии", "физика раньше математики", "порядок неясен"], correctIndex: 1, rationale: "Транзитивность порядка." }),
    q({ id: "g6-l14", itemId: "L6-RC-04", batteryId: "logic_6", grade: 6, domain: "logic_6", subskill: "relation consistency", difficultyLevel: "hard", prompt: "Из «Все олимпиадники решают задачи» что НЕ следует?", options: ["Некоторые решающие задачи — олимпиадники", "Каждый олимпиадник решает задачи", "Если не решает, то не олимпиадник", "Любой решающий задачи — олимпиадник"], correctIndex: 3, rationale: "Отличие достаточного и необходимого." }),
    q({ id: "g6-l15", itemId: "L6-INF-05", batteryId: "logic_6", grade: 6, domain: "logic_6", subskill: "simple/advanced inference", difficultyLevel: "hard", prompt: "«Не верно, что все задачи лёгкие». Что следует?", options: ["все задачи трудные", "некоторые задачи не лёгкие", "ни одна задача не лёгкая", "ровно одна трудная"], correctIndex: 1, rationale: "Кванторное отрицание." }),
    q({ id: "g6-l16", itemId: "L6-CL-04", batteryId: "logic_6", grade: 6, domain: "logic_6", subskill: "classification", difficultyLevel: "medium", prompt: "Какой вариант — логическая ошибка «ложная причина»?", options: ["После талисмана получил 5, значит талисман вызвал 5", "Если выучил — решил", "Все чётные делятся на 2", "Треугольник имеет 3 стороны"], correctIndex: 0, rationale: "Распознавание типа ошибки." }),
    q({ id: "g6-l17", itemId: "L6-OR-04", batteryId: "logic_6", grade: 6, domain: "logic_6", subskill: "ordering", difficultyLevel: "hard", prompt: "В марафоне Петя финишировал позже Коли, но раньше Ильи. Кто из трёх последний?", options: ["Петя", "Коля", "Илья", "нельзя определить"], correctIndex: 2, rationale: "Комбинация отношений «раньше/позже»." }),
    q({ id: "g6-l18", itemId: "L6-RC-05", batteryId: "logic_6", grade: 6, domain: "logic_6", subskill: "relation consistency", difficultyLevel: "medium", prompt: "Если X↔Y истинно, что обязательно?", options: ["X и Y всегда ложны", "X истинно тогда и только тогда, когда Y истинно", "X влечёт не Y", "Y не влечёт X"], correctIndex: 1, rationale: "Бикондиционал." }),
    q({ id: "g6-l19", itemId: "L6-INF-06", batteryId: "logic_6", grade: 6, domain: "logic_6", subskill: "simple/advanced inference", difficultyLevel: "hard", prompt: "Если A→B, B→C и C→D, при истинном A верно:", options: ["D", "не D", "B и не C", "только B"], correctIndex: 0, rationale: "Длинная цепочка вывода." }),
    q({ id: "g6-l20", itemId: "L6-CL-05", batteryId: "logic_6", grade: 6, domain: "logic_6", subskill: "classification", difficultyLevel: "medium", prompt: "Что является контрпримером к фразе «все простые числа нечётные»?", options: ["1", "2", "3", "5"], correctIndex: 1, rationale: "Проверка универсального утверждения." }),

    q({ id: "g6-m1", itemId: "M6-NP-01", batteryId: "math_aptitude_6", grade: 6, domain: "math_aptitude_6", subskill: "number pattern", difficultyLevel: "medium", prompt: "Продолжи: 1, 4, 9, 16, ...", options: ["20", "24", "25", "27"], correctIndex: 2, rationale: "Квадраты натуральных чисел." }),
    q({ id: "g6-m2", itemId: "M6-QC-01", batteryId: "math_aptitude_6", grade: 6, domain: "math_aptitude_6", subskill: "quantity comparison", difficultyLevel: "medium", prompt: "Что больше: 7/12 или 3/5?", options: ["7/12", "3/5", "равны", "нельзя сравнить"], correctIndex: 1, rationale: "Сравнение дробей через общий знаменатель." }),
    q({ id: "g6-m3", itemId: "M6-PR-01", batteryId: "math_aptitude_6", grade: 6, domain: "math_aptitude_6", subskill: "proportional reasoning", difficultyLevel: "medium", prompt: "3 ручки стоят 54 рубля. Сколько стоят 5 таких ручек?", options: ["80", "85", "90", "95"], correctIndex: 2, rationale: "Цена за единицу и масштабирование." }),
    q({ id: "g6-m4", itemId: "M6-SQM-01", batteryId: "math_aptitude_6", grade: 6, domain: "math_aptitude_6", subskill: "structural quantitative modeling", difficultyLevel: "hard", prompt: "Выбери выражение: x тетрадей по 18 руб. и один альбом 70 руб.", options: ["18 + 70x", "18x + 70", "70x + 18", "18x - 70"], correctIndex: 1, rationale: "Моделирование текстового условия." }),
    q({ id: "g6-m5", itemId: "M6-SQR-01", batteryId: "math_aptitude_6", grade: 6, domain: "math_aptitude_6", subskill: "spatial-quantitative reasoning", difficultyLevel: "hard", prompt: "Периметр квадрата 40 см. Какова площадь?", options: ["80", "90", "100", "120"], correctIndex: 2, rationale: "Связь периметра и стороны." }),
    q({ id: "g6-m6", itemId: "M6-NP-02", batteryId: "math_aptitude_6", grade: 6, domain: "math_aptitude_6", subskill: "number pattern", difficultyLevel: "hard", prompt: "2, 5, 11, 23, ...", options: ["35", "41", "47", "49"], correctIndex: 2, rationale: "Правило ×2+1." }),
    q({ id: "g6-m7", itemId: "M6-QC-02", batteryId: "math_aptitude_6", grade: 6, domain: "math_aptitude_6", subskill: "quantity comparison", difficultyLevel: "easy", prompt: "Какое число ближе к 1: 0,93 или 0,87?", options: ["0,93", "0,87", "одинаково", "сравнить нельзя"], correctIndex: 0, rationale: "Сравнение расстояний до единицы." }),
    q({ id: "g6-m8", itemId: "M6-PR-02", batteryId: "math_aptitude_6", grade: 6, domain: "math_aptitude_6", subskill: "proportional reasoning", difficultyLevel: "hard", prompt: "Скорость выросла с 48 до 72 км/ч. Во сколько раз?", options: ["1,25", "1,5", "1,75", "2"], correctIndex: 1, rationale: "Отношение новой к старой величине." }),
    q({ id: "g6-m9", itemId: "M6-SQM-02", batteryId: "math_aptitude_6", grade: 6, domain: "math_aptitude_6", subskill: "structural quantitative modeling", difficultyLevel: "medium", prompt: "Реши: 4x + 7 = 31", options: ["5", "6", "7", "8"], correctIndex: 1, rationale: "Линейное уравнение." }),
    q({ id: "g6-m10", itemId: "M6-SQR-02", batteryId: "math_aptitude_6", grade: 6, domain: "math_aptitude_6", subskill: "spatial-quantitative reasoning", difficultyLevel: "medium", prompt: "Сколько диагоналей у шестиугольника?", options: ["6", "7", "8", "9"], correctIndex: 3, rationale: "n(n-3)/2 для n=6." }),
    q({ id: "g6-m11", itemId: "M6-NP-03", batteryId: "math_aptitude_6", grade: 6, domain: "math_aptitude_6", subskill: "number pattern", difficultyLevel: "medium", prompt: "7, 11, 15, ...", options: ["17", "18", "19", "20"], correctIndex: 2, rationale: "Арифметическая прогрессия d=4." }),
    q({ id: "g6-m12", itemId: "M6-QC-03", batteryId: "math_aptitude_6", grade: 6, domain: "math_aptitude_6", subskill: "quantity comparison", difficultyLevel: "hard", prompt: "Что больше: 35% от 200 или 70?", options: ["35% от 200", "70", "равны", "нельзя сравнить"], correctIndex: 2, rationale: "Проверка процентного эквивалента." }),
    q({ id: "g6-m13", itemId: "M6-PR-03", batteryId: "math_aptitude_6", grade: 6, domain: "math_aptitude_6", subskill: "proportional reasoning", difficultyLevel: "hard", prompt: "На карте 1 см = 5 км. Чему соответствуют 3,6 см?", options: ["12 км", "15 км", "18 км", "20 км"], correctIndex: 2, rationale: "Масштаб и пропорция." }),
    q({ id: "g6-m14", itemId: "M6-SQM-03", batteryId: "math_aptitude_6", grade: 6, domain: "math_aptitude_6", subskill: "structural quantitative modeling", difficultyLevel: "hard", prompt: "В урне красных шаров в 2 раза больше, чем синих. Всего 18 шаров. Сколько синих?", options: ["4", "6", "8", "12"], correctIndex: 1, rationale: "Система x+2x=18." }),
    q({ id: "g6-m15", itemId: "M6-SQR-03", batteryId: "math_aptitude_6", grade: 6, domain: "math_aptitude_6", subskill: "spatial-quantitative reasoning", difficultyLevel: "hard", prompt: "Объём прямоугольного параллелепипеда 60 см³, размеры основания 5 см и 3 см. Высота равна:", options: ["2", "3", "4", "5"], correctIndex: 2, rationale: "V=abc, 60/(5*3)=4." }),
    q({ id: "g6-m16", itemId: "M6-NP-04", batteryId: "math_aptitude_6", grade: 6, domain: "math_aptitude_6", subskill: "number pattern", difficultyLevel: "hard", prompt: "3, 9, 21, 45, ...", options: ["81", "87", "93", "99"], correctIndex: 2, rationale: "Правило ×2+3." }),
    q({ id: "g6-m17", itemId: "M6-QC-04", batteryId: "math_aptitude_6", grade: 6, domain: "math_aptitude_6", subskill: "quantity comparison", difficultyLevel: "medium", prompt: "Что больше: 2/3 от 27 или 3/4 от 24?", options: ["2/3 от 27", "3/4 от 24", "равны", "нельзя сравнить"], correctIndex: 2, rationale: "Обе величины равны 18." }),
    q({ id: "g6-m18", itemId: "M6-PR-04", batteryId: "math_aptitude_6", grade: 6, domain: "math_aptitude_6", subskill: "proportional reasoning", difficultyLevel: "medium", prompt: "За 4 часа изготовили 28 деталей при постоянном темпе. Сколько за 6 часов?", options: ["36", "40", "42", "48"], correctIndex: 2, rationale: "Прямая пропорция по времени." }),
    q({ id: "g6-m19", itemId: "M6-SQM-04", batteryId: "math_aptitude_6", grade: 6, domain: "math_aptitude_6", subskill: "structural quantitative modeling", difficultyLevel: "hard", prompt: "Составь и реши: «число увеличили на 15% и получили 69». Исходное число:", options: ["50", "55", "60", "65"], correctIndex: 2, rationale: "1.15x=69 => x=60." }),
    q({ id: "g6-m20", itemId: "M6-SQR-04", batteryId: "math_aptitude_6", grade: 6, domain: "math_aptitude_6", subskill: "spatial-quantitative reasoning", difficultyLevel: "medium", prompt: "Площадь прямоугольника 54 см², одна сторона 6 см. Вторая сторона:", options: ["7", "8", "9", "10"], correctIndex: 2, rationale: "S=ab => 54/6=9." }),
  ],
};
